# Docker Compose override for development environment
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: "3.8"

services:
  roulette-api:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOG_LEVEL_ROOT=DEBUG
      - LOG_LEVEL_CASINO=DEBUG
    volumes:
      - ./src:/app/src:ro # Mount source for hot reload in dev
      - ./logs:/app/logs
    ports:
      - "8080:8080"
      - "5005:5005" # Debug port
    command: >
      sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
             $$JVM_OPTS -jar app.jar"

  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=casino_roulette_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  redis:
    ports:
      - "6379:6379"

volumes:
  postgres_dev_data:
    driver: local
