spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/casino_roulette
    username: mstrong
    password: tlacjfqhr326
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

  # Redis
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

server:
  port: 8080
  servlet:
    context-path: /api

# CORS configuration for development
cors:
  allowed-origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://localhost:5173"  # Vite default port
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
    - "http://127.0.0.1:8081"
    - "http://127.0.0.1:5173"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  allowed-headers: "*"
  allow-credentials: false
  max-age: 3600

logging:
  level:
    root: INFO
    com.casino: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always